### PR TITLE
I've added support to Unicode Send email

### PR DESCRIPTION
**Pull request by PVLopes**
Tested on Windows 7 x64 and Windows 10 x64 with Outlook 32/64 bit.

### CODE REVIEW

**Comment by PandaWood** [comment]
Thank this looks useful. I hadn't noticed a lack of support for unicode.
Should I test it by including non ANSI characters in the subject or body, for example テスト ?

**Comment by PVLopes** [comment]
I've tested with unicode chars in the subject, body and recipient email.

**Comment by PVLopes** [comment]
On Windows 7 some unicode characters will be translated to question marks, due to the lack of unicode support on the MAPI.
Others, like ž, will be translated to their ansi equivalents, in this case z.

**Comment by PandaWood** [comment]
Right, thanks. I'll give it a quick sanity test this weekend sometime and then merge it in.

**Comment by Jonney3099** [comment]
Good to see unicode support!
Only my gmail said "Message clipped" when body has Unicode chars though it is OK actually. Other mails (my personal one) show no such info.

Gmail:
> hi my custom Language file, 中文Cheers!
> ...
> 
> [Message clipped]  View entire message

**Comment by PandaWood** [comment]
Apologies for the delay, I didn't have a Windows setup for a while. Will come back to this shortly

**Pull request merged**
